language: node_js
node_js:
  - "stable"
 dist: focal
branch:
  only:
  - main
cache:
  directories:
  -node_modules
install:
  -npm install
  -npm install -g yarn
script:
  -yarn build
  -mv build/index.html build404/.html
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $github_token
  local_dir: build
  on:
    branch: main


